# Generated by Django 5.0.6 on 2024-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='product_img/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('promo_price', models.FloatField(default=0)),
                ('p_type', models.CharField(choices=[('V', 'variation'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
