# Generated by Django 5.0.6 on 2024-06-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_imagem_product_image_rename_nome_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='description',
        ),
    ]
