# Generated by Django 5.0.6 on 2024-06-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_producttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
    ]
