# Generated by Django 5.0.6 on 2024-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='promo_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
