# Generated by Django 5.0.6 on 2024-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_producttype_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
