# Generated by Django 5.0.6 on 2024-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_producttype_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='promo_price',
            field=models.FloatField(default=0),
        ),
    ]
