# Generated by Django 5.0.6 on 2024-06-10 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('cc', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('LI', 'Lisboa'), ('PO', 'Porto'), ('SE', 'Setubal'), ('BR', 'Braga'), ('AV', 'Aveiro'), ('FA', 'Faro'), ('LE', 'Leiria'), ('SA', 'Santarém'), ('CO', 'Coimbra'), ('VI', 'Viseu'), ('MA', 'Madeira'), ('AÇ', 'Açores'), ('VC', 'Viana Do Castelo'), ('VR', 'Vila Real'), ('CB', 'Castelo Branco'), ('EV', 'Évora'), ('BE', 'Beja'), ('GU', 'Guarda'), ('BG', 'Bragança'), ('PO', 'Portalegre')], default='LI', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
